# Generated by Django 5.2.7 on 2025-11-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TBCarsWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carname', models.CharField(max_length=100, unique=True)),
                ('carbrand', models.CharField(max_length=100)),
                ('carmodel', models.CharField(max_length=100)),
                ('carprice', models.CharField(max_length=50)),
            ],
        ),
    ]
